### ISSUE TITLE
chown commad not working 

### ISSUE THREAD

**Issue by abhishek8908** [jpalomaki/simple-ssh-client#1]
Hi I was trying some commands like chown , however the ownership is not reflecting after the execution. Could you please help?

   ```
 @Test
    public void testMyssh3(){


        UserAtHost userAtHost = new UserAtHost("asingh", "parasoft.test.igdcs.com");
        SshClient sshClient = new JschSshClient("~/.ssh/id_rsa", "passphrase");

        // sshClient.executeCommand("cd /export/parasoft/apache-tomcat-8.5.29-ctp/", userAtHost);
        Result result= sshClient.executeCommand("sudo chown -R <user>:<group> /export/parasoft/test1", userAtHost);

        String uname = result.stdoutAsText();
        System.out.println(uname);

    }
```

**Comment by jpalomaki** [comment]
Apologies for the late reply. Unfortunately this project is no longer maintained (I should've archived it long ago).

However, I suspect your particular issue might have something to do with either sudo password or PTY allocation.

I propose you look at a more recent version of Jsch (which this project is based on), e.g. http://www.jcraft.com/jsch/examples/Sudo.java.html.

You may also find more up-to-date wrappers for Jsch, or other Java SSH alternatives via Google: https://www.google.fi/search?q=java+ssh

I will update the README in this repo to reflect the fact that this project is no longer maintained and then archive it.
